name: Continuous-integration

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  verify:
    name: Verify
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: "12"
    - name: Install dependencies
      run: npm i
    - name: Run tests
      run: npm run test
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

  dogfood-linux:
    name: Dogfood (ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Grafana Tanka
      uses: ./
      with:
        tanka-version: 0.18.1
    - name: Show the Grafana Tanka version
      run: |
        version="$(tk --version)"
        echo $version

        if [[ $version =~ "tk version v0.18.1" ]]; then
          exit 1
        fi

  dogfood-windows:
    name: Dogfood (windows-latest)
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Grafana Tanka
      uses: ./
      with:
        tanka-version: 0.18.1
    - name: Show the Grafana Tanka version
      run: |
        tk.exe --version
