name: Continuous-integration

on:
  push:
    branches:
    - main

jobs:
  dogfooding:
    name: Dogfooding
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Grafana Tanka
      uses: ./
      with:
        tanka-version: 0.16.0
    - name: Show the Grafana Tanka version
      run: tk --version
