name: Continuous-integration

on:
  push:
    branches:
    - main

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: "12"
    - name: Install dependencies
      run: npm i
    - name: Run tests
      run: npm run test

  dogfood:
    name: Dogfood
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Grafana Tanka
      uses: ./
      with:
        tanka-version: 0.16.0
    - name: Show the Grafana Tanka version
      run: tk --version
